SELECT
P.TITLE, S.ORDER_DATE,SUM(S.SALES) AS TOTAL_SALES
FROM (
SELECT PRODUCT_ID, CAST(O.CREATED_AT AS DATE) AS ORDER_DATE,ROUND(SUM(TOTAL_PRICE),2) AS SALES
FROM "FIVETRAN_DATABASE"."SHOPIFY_DS"."ORDER_LINE" OL
LEFT JOIN "FIVETRAN_DATABASE"."SHOPIFY_DS"."ORDER" O 
ON O.ID = OL.ORDER_ID
group by 1,2
)S
LEFT JOIN "FIVETRAN_DATABASE"."SHOPIFY_DS"."PRODUCT" P 
ON S.PRODUCT_ID = P.ID
WHERE P.TITLE IS NOT NULL
GROUP BY 1,2
ORDER BY 3 DESC